name: Pull request main (workflows)

on:
  push:
    branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: docker build
          run: docker build -t my-image .

        - name: docker run my-image
          run: docker run my-image
